Feat/challenge 1
ZilongZhan/Javascript-callbacks pull request #1
Opened 2023-12-10 03:45 UTC by ZilongZhan

Sorry for party rocking

2023-12-10 18:55 UTC, tictools requested changes

2023-12-10 18:55 UTC, tictools commented on exercise_01/transformStringToCollection.test.js
> +      expect(result.length).toBeGreaterThan(0);
```suggestion
      expect(result.length).toBe(2);
```

2023-12-10 18:55 UTC, tictools commented on exercise_02/createUser.test.js
> +      expect(typeof result).toBe("string");
This is a good test, but it is not testing success case... because error case also returns a string. 😉

2023-12-18 18:29 UTC, Maarcfleckk commented on helpers/validateString.js
> +export const validateString = (value) => {
Function's signature is missing. Needs work. Fix it 🚀🧠🚀

2024-01-07 10:59 UTC, tictools approved these changes

2024-01-08 17:43 UTC, Maarcfleckk approved these changes

2024-01-09 17:49 UTC, merged